@startuml
'https://plantuml.com/class-diagram

interface Routes.Interface
interface Controller.Interface
interface DAO.Interface
interface Service.Interface
interface Facotory.Interface
abstract class Routes.Methods
abstract class Controller.Methods
abstract class DAO.Methods



List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml