@startuml
'https://plantuml.com/class-diagram

'abstract class Methods
abstract Methods implements Interface
class Entity implements DataUnit
record Record implements DataUnit
interface Interface
interface DataUnit

class TestData{
'Global Fields
- Entity globalEntity
- Record globalRecord
+ TestData instance

- TestData()
+ TestData getInstance()
+ abstract class Methods()
- interface Interface()
- class Entity()
}

class Entity{
- Integer id
- String name
Entity(String name)
- Integer getId()
+ toString()
}

abstract class Methods{
- Methods()
- <Data extends DataUnit> create(Class<Data>)
- Class<? extends DataUnit> getUnitClass(DataType type)
+ DataUnit constructor(DataType data, String name)
+ Class<? extends Entity> dataUnitToEntity(DataUnit data)
+ Class<? extends Record> dataUnitToRecord(DataUnit data)
+ Entity getEntity()
+ putEntity(Entity value)
+ Record getRecord()
+ putRecord(Record value)
+ Record putRecord
}

@enduml